=== StefanieSchmidiger/BDA/SwTreiber/IODD/IO_Device_Description_V1.1_Specification/Schemas/IODD-Primitives1.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.io-link.com/IODD/2010/10" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:iodd="http://www.io-link.com/IODD/2010/10" targetNamespace="http://www.io-link.com/IODD/2010/10" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.1">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
	<xsd:simpleType name="IdT">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Za-z][A-Za-z0-9 _-]*[A-Za-z0-9]"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RefT">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Za-z][A-Za-z0-9 _-]*[A-Za-z0-9]"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="SubindexT">
		<xsd:restriction base="xsd:unsignedByte">
			<xsd:minInclusive value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="BitCountT">
		<xsd:restriction base="xsd:unsignedShort"/>
	</xsd:simpleType>
	<xsd:simpleType name="IsduLengthT">
		<xsd:restriction base="xsd:unsignedByte">
			<xsd:minInclusive value="1"/>
			<xsd:maxInclusive value="232"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DeviceIdT">
		<xsd:restriction base="xsd:unsignedInt">
			<xsd:minInclusive value="1"/>
			<xsd:maxInclusive value="16777215"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CharacterEncodingT">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="UTF-8"/>
			<xsd:enumeration value="US-ASCII"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="VersionT">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="V\d+(\.\d+){1,7}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="AccessRightsT">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ro"/>
			<xsd:enumeration value="rw"/>
			<xsd:enumeration value="wo"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="TextDefinitionT">
		<xsd:attribute name="id" type="IdT" use="required"/>
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="TextRefT">
		<xsd:attribute name="textId" type="RefT" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="CollectionT"/>
	<xsd:complexType name="StampT">
		<xsd:sequence>
			<xsd:element name="Checker">
				<xsd:complexType>
					<xsd:attribute name="name" type="xsd:string" use="required"/>
					<xsd:attribute name="version" type="VersionT" use="required"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="crc" type="xsd:unsignedInt" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="ConditionT">
		<xsd:attribute name="variableId" type="RefT" use="required"/>
		<xsd:attribute name="subindex" type="SubindexT"/>
		<xsd:attribute name="value" type="xsd:unsignedByte" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="ExternalTextCollectionT">
		<xsd:complexContent>
			<xsd:extension base="CollectionT">
				<xsd:sequence>
					<xsd:element name="PrimaryLanguage" type="PrimaryLanguageT">
						<xsd:unique name="Primary_LanguageRedefine_id">
							<xsd:selector xpath="iodd:TextRedefine"/>
							<xsd:field xpath="@id"/>
						</xsd:unique>
					</xsd:element>
					<xsd:element name="Language" type="LanguageT" minOccurs="0" maxOccurs="unbounded">
						<xsd:unique name="Language_id">
							<xsd:selector xpath="iodd:Text"/>
							<xsd:field xpath="@id"/>
						</xsd:unique>
						<xsd:unique name="LanguageRedefine_id">
							<xsd:selector xpath="iodd:TextRedefine"/>
							<xsd:field xpath="@id"/>
						</xsd:unique>
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="DocumentInfoT">
		<xsd:annotation>
			<xsd:documentation>This type defines document information.</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="version" type="VersionT" use="required"/>
		<xsd:attribute name="releaseDate" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:date">
					<xsd:pattern value="\d{4}-\d{2}-\d{2}"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="copyright" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="ObjectT">
		<xsd:attribute name="id" type="IdT" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="ExternalTextDocumentT">
		<xsd:annotation>
			<xsd:documentation>This type defines the structure of the file that contains external language dependent text definitions. One file can contain texts of only one language.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="DocumentInfo" type="DocumentInfoT" minOccurs="0"/>
			<xsd:element name="Language" type="LanguageT">
				<xsd:unique name="ExternalTextDocument_Language_id">
					<xsd:selector xpath="iodd:Text"/>
					<xsd:field xpath="@id"/>
				</xsd:unique>
				<xsd:unique name="ExternalTextDocument_LanguageRedefine_id">
					<xsd:selector xpath="iodd:TextRedefine"/>
					<xsd:field xpath="@id"/>
				</xsd:unique>
			</xsd:element>
			<xsd:element name="Stamp" type="StampT">
				<xsd:annotation>
					<xsd:documentation>Filled out by the IODD Checker.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="ExternalTextDocument" type="ExternalTextDocumentT">
		<xsd:annotation>
			<xsd:documentation>This defines the root element of the file that contains external text definitions.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="LanguageT">
		<xsd:choice maxOccurs="unbounded">
			<xsd:element name="Text" type="TextDefinitionT"/>
			<xsd:element name="TextRedefine" type="TextDefinitionT"/>
		</xsd:choice>
		<xsd:attribute ref="xml:lang" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="PrimaryLanguageT">
		<xsd:complexContent>
			<xsd:restriction base="LanguageT">
				<xsd:choice maxOccurs="unbounded">
					<xsd:element name="Text" type="TextDefinitionT"/>
					<xsd:element name="TextRedefine" type="TextDefinitionT"/>
				</xsd:choice>
			</xsd:restriction>
			<!-- <xsd:attribute ref="xml:lang" use="required" fixed="en"/> -->
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>

=== StefanieSchmidiger/BDA/SwTreiber/IODD/IO_Device_Description_V1.1_Specification/StandardDefinitions/IODD-StandardUnitDefinitions1.1-fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<ExternalTextDocument xmlns="http://www.io-link.com/IODD/2010/10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.io-link.com/IODD/2010/10 IODD-Primitives1.1.xsd">
	<DocumentInfo version="V1.1" releaseDate="2011-08-08" copyright="IO-Link Consortium"/>
	<Language xml:lang="fr">
		<!-- 0 - 999 Reserved -->
		<Text id="STD_T_1000" value="Kelvin"/>
		<Text id="STD_T_1001" value="degré Celsius"/>
		<Text id="STD_T_1002" value="degré Fahrenheit"/>
		<Text id="STD_T_1003" value="degré Rankine"/>
		<Text id="STD_T_1004" value="radian"/>
		<Text id="STD_T_1005" value="degré"/>
		<Text id="STD_T_1006" value="minute"/>
		<Text id="STD_T_1007" value="seconde"/>
		<Text id="STD_T_1008" value="gon (ou grade)"/>
		<Text id="STD_T_1009" value="tour"/>
		<Text id="STD_T_1010" value="mètre"/>
		<Text id="STD_T_1011" value="kilomètre"/>
		<Text id="STD_T_1012" value="centimètre"/>
		<Text id="STD_T_1013" value="millimètre"/>
		<Text id="STD_T_1014" value="micromètre"/>
		<Text id="STD_T_1015" value="nanomètre"/>
		<Text id="STD_T_1016" value="picomètre"/>
		<Text id="STD_T_1017" value="ängström"/>
		<Text id="STD_T_1018" value="pied"/>
		<Text id="STD_T_1019" value="pouce"/>
		<Text id="STD_T_1020" value="yard"/>
		<Text id="STD_T_1021" value="mille"/>
		<Text id="STD_T_1022" value="mille nautique"/>
		<Text id="STD_T_1023" value="mètre carré"/>
		<Text id="STD_T_1024" value="kilomètre carré"/>
		<Text id="STD_T_1025" value="centimètre carré"/>
		<Text id="STD_T_1026" value="décimètre carré"/>
		<Text id="STD_T_1027" value="millimètre carré"/>
		<Text id="STD_T_1028" value="are"/>
		<Text id="STD_T_1029" value="hectare"/>
		<Text id="STD_T_1030" value="pouce carré"/>
		<Text id="STD_T_1031" value="pied carré"/>
		<Text id="STD_T_1032" value="yard carré"/>
		<Text id="STD_T_1033" value="mille carré"/>
		<Text id="STD_T_1034" value="mètre cube"/>
		<Text id="STD_T_1035" value="décimètre cube"/>
		<Text id="STD_T_1036" value="centimètre cube"/>
		<Text id="STD_T_1037" value="millimètre cube"/>
		<Text id="STD_T_1038" value="litre"/>
		<Text id="STD_T_1039" value="centilitre"/>
		<Text id="STD_T_1040" value="millilitre"/>
		<Text id="STD_T_1041" value="hectolitre"/>
		<Text id="STD_T_1042" value="pouce cube"/>
		<Text id="STD_T_1043" value="pieds cubes"/>
		<Text id="STD_T_1044" value="yard cube"/>
		<Text id="STD_T_1045" value="mille cube"/>
		<Text id="STD_T_1046" value="pinte américaine"/>
		<Text id="STD_T_1047" value="quart américain"/>
		<Text id="STD_T_1048" value="gallon américain"/>
		<Text id="STD_T_1049" value="gallon impérial"/>
		<Text id="STD_T_1050" value="boisseau (matière sèche)"/>
		<Text id="STD_T_1051" value="baril de pétrol américain"/>
		<Text id="STD_T_1052" value="baril liquide (américain)"/>
		<Text id="STD_T_1053" value="pied cube standard"/>
		<Text id="STD_T_1054" value="seconde"/>
		<Text id="STD_T_1055" value="kiloseconde"/>
		<Text id="STD_T_1056" value="milliseconde"/>
		<Text id="STD_T_1057" value="microseconde"/>
		<Text id="STD_T_1058" value="minute"/>
		<Text id="STD_T_1059" value="heure"/>
		<Text id="STD_T_1060" value="jour"/>
		<Text id="STD_T_1061" value="mètre par seconde"/>
		<Text id="STD_T_1062" value="millimètre par seconde"/>
		<Text id="STD_T_1063" value="mètre par heure"/>
		<Text id="STD_T_1064" value="kilomètre par heure"/>
		<Text id="STD_T_1065" value="mille nautique par heure"/>
		<Text id="STD_T_1066" value="pouce par seconde"/>
		<Text id="STD_T_1067" value="pied par seconde"/>
		<Text id="STD_T_1068" value="yard par seconde"/>
		<Text id="STD_T_1069" value="pouce par minute"/>
		<Text id="STD_T_1070" value="pied par minute"/>
		<Text id="STD_T_1071" value="yard par minute"/>
		<Text id="STD_T_1072" value="pouce par heure"/>
		<Text id="STD_T_1073" value="pied par heure"/>
		<Text id="STD_T_1074" value="yard par heure"/>
		<Text id="STD_T_1075" value="mile par heure"/>
		<Text id="STD_T_1076" value="mètre par seconde carré"/>
		<Text id="STD_T_1077" value="hertz"/>
		<Text id="STD_T_1078" value="térahertz"/>
		<Text id="STD_T_1079" value="gigahertz"/>
		<Text id="STD_T_1080" value="mégahertz"/>
		<Text id="STD_T_1081" value="kilohertz"/>
		<Text id="STD_T_1082" value="par seconde"/>
		<Text id="STD_T_1083" value="par minute"/>
		<Text id="STD_T_1084" value="tour par seconde"/>
		<Text id="STD_T_1085" value="tour par minute"/>
		<Text id="STD_T_1086" value="radian par seconde"/>
		<Text id="STD_T_1087" value="par seconde carré"/>
		<Text id="STD_T_1088" value="kilogramme"/>
		<Text id="STD_T_1089" value="gramme"/>
		<Text id="STD_T_1090" value="milligramme"/>
		<Text id="STD_T_1091" value="mégagramme"/>
		<Text id="STD_T_1092" value="tonne métrique"/>
		<Text id="STD_T_1093" value="once"/>
		<Text id="STD_T_1094" value="livre"/>
		<Text id="STD_T_1095" value="tonne courte"/>
		<Text id="STD_T_1096" value="tonne longue"/>
		<Text id="STD_T_1097" value="kilogramme par mètre cube"/>
		<Text id="STD_T_1098" value="mégagramme par mètre cube"/>
		<Text id="STD_T_1099" value="kilogramme par décimètre cube"/>
		<Text id="STD_T_1100" value="gramme par centimètre cube"/>
		<Text id="STD_T_1101" value="gramme par mètre cube"/>
		<Text id="STD_T_1102" value="tonne métrique par mètre cube"/>
		<Text id="STD_T_1103" value="kilogramme par litre"/>
		<Text id="STD_T_1104" value="gramme par millilitre"/>
		<Text id="STD_T_1105" value="gramme par litre"/>
		<Text id="STD_T_1106" value="livre par pouce cube"/>
		<Text id="STD_T_1107" value="livre par pied cube"/>
		<Text id="STD_T_1108" value="livre par gallon américain"/>
		<Text id="STD_T_1109" value="tonne courte par yard cube"/>
		<Text id="STD_T_1110" value="degré Twaddell"/>
		<Text id="STD_T_1111" value="degré baumé lourd"/>
		<Text id="STD_T_1112" value="degré baumé légère"/>
		<Text id="STD_T_1113" value="degré API"/>
		<Text id="STD_T_1114" value="unité de gravité spécifique"/>
		<Text id="STD_T_1115" value="kilogramme par mètre"/>
		<Text id="STD_T_1116" value="milligramme par mètre"/>
		<Text id="STD_T_1117" value="tex"/>
		<Text id="STD_T_1118" value="kilogramme par mètre carré"/>
		<Text id="STD_T_1119" value="kilogrammètre par seconde"/>
		<Text id="STD_T_1120" value="newton"/>
		<Text id="STD_T_1121" value="méganewton"/>
		<Text id="STD_T_1122" value="kilonewton"/>
		<Text id="STD_T_1123" value="millinewton"/>
		<Text id="STD_T_1124" value="micronewton"/>
		<Text id="STD_T_1125" value="kilogrammètre carré par seconde"/>
		<Text id="STD_T_1126" value="newton mètre"/>
		<Text id="STD_T_1127" value="méganewton mètre"/>
		<Text id="STD_T_1128" value="kilonewton mètre"/>
		<Text id="STD_T_1129" value="millinewton mètre"/>
		<Text id="STD_T_1130" value="pascal"/>
		<Text id="STD_T_1131" value="gigapascal"/>
		<Text id="STD_T_1132" value="mégapascal"/>
		<Text id="STD_T_1133" value="kilopascal"/>
		<Text id="STD_T_1134" value="millipascal"/>
		<Text id="STD_T_1135" value="micropascal"/>
		<Text id="STD_T_1136" value="hectopascal"/>
		<Text id="STD_T_1137" value="bar"/>
		<Text id="STD_T_1138" value="millibar"/>
		<Text id="STD_T_1139" value="torr"/>
		<Text id="STD_T_1140" value="atmosphère"/>
		<Text id="STD_T_1141" value="livre-force par pouce carré"/>
		<Text id="STD_T_1142" value="livre-force par pouce carré absolu"/>
		<Text id="STD_T_1143" value="livre-force par pouce carré relatif"/>
		<Text id="STD_T_1144" value="gramme-force par centimètre carré"/>
		<Text id="STD_T_1145" value="kilogramme-force par centimètre carré"/>
		<Text id="STD_T_1146" value="pouces d'eau"/>
		<Text id="STD_T_1147" value="pouces d'eau à 4°C"/>
		<Text id="STD_T_1148" value="pouces d'eau à 68°F"/>
		<Text id="STD_T_1149" value="millimètre d'eau"/>
		<Text id="STD_T_1150" value="millimètre d'eau à 4°C"/>
		<Text id="STD_T_1151" value="millimètre d'eau à 68°F"/>
		<Text id="STD_T_1152" value="pied d'eau"/>
		<Text id="STD_T_1153" value="pied d'eau à 4°C"/>
		<Text id="STD_T_1154" value="pied d'eau à 68°F"/>
		<Text id="STD_T_1155" value="pouce de mercure"/>
		<Text id="STD_T_1156" value="pouce de mercure à 0°C"/>
		<Text id="STD_T_1157" value="millimètre de mercure"/>
		<Text id="STD_T_1158" value="millimètre de mercure à 0°C"/>
		<Text id="STD_T_1159" value="pascal-seconde"/>
		<Text id="STD_T_1160" value="mètre carré par seconde"/>
		<Text id="STD_T_1161" value="poise"/>
		<Text id="STD_T_1162" value="centipoise"/>
		<Text id="STD_T_1163" value="stoke"/>
		<Text id="STD_T_1164" value="centistoke"/>
		<Text id="STD_T_1165" value="newton par mètre"/>
		<Text id="STD_T_1166" value="millinewton par mètre"/>
		<Text id="STD_T_1167" value="joule"/>
		<Text id="STD_T_1168" value="exajoule"/>
		<Text id="STD_T_1169" value="pétajoule"/>
		<Text id="STD_T_1170" value="térajoule"/>
		<Text id="STD_T_1171" value="gigajoule"/>
		<Text id="STD_T_1172" value="mégajoule"/>
		<Text id="STD_T_1173" value="kilojoule"/>
		<Text id="STD_T_1174" value="millijoule"/>
		<Text id="STD_T_1175" value="wattheure"/>
		<Text id="STD_T_1176" value="térawatt-heure"/>
		<Text id="STD_T_1177" value="gigiawatt-heure"/>
		<Text id="STD_T_1178" value="mégawatt-heure"/>
		<Text id="STD_T_1179" value="kilowatt-heure"/>
		<Text id="STD_T_1180" value="calorie"/>
		<Text id="STD_T_1181" value="kilocalorie"/>
		<Text id="STD_T_1182" value="mégacalorie"/>
		<Text id="STD_T_1183" value="unité thermique britannique"/>
		<Text id="STD_T_1184" value="decatherm"/>
		<Text id="STD_T_1185" value="livre-force pied"/>
		<Text id="STD_T_1186" value="watt"/>
		<Text id="STD_T_1187" value="térawatt"/>
		<Text id="STD_T_1188" value="gigawatt"/>
		<Text id="STD_T_1189" value="mégawatt"/>
		<Text id="STD_T_1190" value="kilowatt"/>
		<Text id="STD_T_1191" value="milliwatt"/>
		<Text id="STD_T_1192" value="microwatt"/>
		<Text id="STD_T_1193" value="nanowatt"/>
		<Text id="STD_T_1194" value="picowatt"/>
		<Text id="STD_T_1195" value="mégacalorie par heure"/>
		<Text id="STD_T_1196" value="mégajoule par heure"/>
